version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: jphack_front

  qrally:
    build:
      context: .
      dockerfile: QR_alert/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./QR_alert:/app
      - qrally_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: qrally_service

volumes:
  frontend_node_modules:
  qrally_node_modules:
